openapi: 3.1.0
info:
  title: Notion Meeting Agent API
  version: 1.3.1
  description: Cloud API for creating and managing meeting notes synced with Notion.
servers:
  - url: https://notion-meeting-agent-vercel.vercel.app
paths:
  /meetings.create:
    post:
      summary: Create a new meeting record in Notion.
      operationId: createMeeting
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: Meeting title
                date:
                  type: string
                  format: date
                start:
                  type: string
                  description: Start time (HH:MM) alias for start_time
                end:
                  type: string
                  description: End time (HH:MM) alias for end_time
                attendees:
                  type: string
                meeting_type:
                  type: string
                discussion:
                  type: string
                conclusion:
                  type: string
                todo:
                  type: string
                status:
                  type: string
              required:
                - title
                - date
                - start
                - end
      responses:
        '200':
          description: Successful creation
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                  message:
                    type: string
                  meeting:
                    type: object
                    properties:
                      title:
                        type: string
                      date:
                        type: string
                      start:
                        type: string
                      end:
                        type: string
